# Generated by Django 3.0.5 on 2020-04-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_store',
            name='added_by',
        ),
    ]
